### PR TITLE
staging merge to live-based414

### PR DESCRIPTION
**Pull request by opse2esa**
# PR Summary

## PR Context

Select the type(s) of documents being changed.

**Cmdlet reference & about_ topics**
- [ ] Version 7.x preview content
- [ ] Version 7.0 content
- [ ] Version 6 content
- [ ] Version 5.1 content

**Conceptual articles**
- [ ] Fundamental conceptual articles
- [ ] Script sample articles
- [ ] DSC articles
- [ ] Gallery articles
- [ ] JEA articles
- [ ] WMF articles
- [ ] SDK articles

## PR Checklist

- [ ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ ] PR has a meaningful title
- [ ] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[b321069](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/b3210691a5791640f38005212649a24f65188050)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aaf18c22)

<a id="aaf18c22"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\owyv-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: b3210691a5791640f38005212649a24f65188050.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004140111281046-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5NQzknOfP5TpARKuDljDpmQJ1qzbt6EQlUUvLv0oGqs%3D&st=2020-04-14T01%3A06%3A51Z&se=2020-05-15T01%3A11%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[b321069](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/b3210691a5791640f38005212649a24f65188050)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c11756f8)

<a id="c11756f8"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\2gp3-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: b3210691a5791640f38005212649a24f65188050.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004140648568914-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ewgeMPu0s4ZyZ44dQb6%2BpVvBfMyxfscIO%2FTmHlFuYIg%3D&st=2020-04-14T06%3A44%3A36Z&se=2020-05-15T06%3A49%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[30c82de](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/30c82de468551d661877378f9ad9815a8fadcf3f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-79e6f5e3)

<a id="79e6f5e3"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\wh0x-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 30c82de468551d661877378f9ad9815a8fadcf3f.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004141959319275-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=chGxJf%2FBhm2A%2F9b%2FVU29GJbs76i92xGmQItSGAgw6dw%3D&st=2020-04-14T19%3A55%3A11Z&se=2020-05-15T20%3A00%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[6a8fda3](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/6a8fda351b5d963e65ef4aa230d8b73608ec1f87)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5fd5c8d3)

<a id="5fd5c8d3"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\2qem-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 6a8fda351b5d963e65ef4aa230d8b73608ec1f87.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004142217509831-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7YjCOwOMQqLrg0dXpivKqUuzQVkzXxRLW7zgMJIwqS8%3D&st=2020-04-14T22%3A13%3A31Z&se=2020-05-15T22%3A18%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[c9aeb09](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/c9aeb09ffce68a3ad0828ae1846877ac93e41ffc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3c0390d0)

<a id="3c0390d0"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\daei-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: c9aeb09ffce68a3ad0828ae1846877ac93e41ffc.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004142310242737-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vZ6JZ67o6wo9S6XMz55PDFaJTO2gDTxjZX6iaJLSuAg%3D&st=2020-04-14T23%3A06%3A04Z&se=2020-05-15T23%3A11%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[a746ba8](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/a746ba8924442de46987f7811e4a49c3701df639)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4be1fb51)

<a id="4be1fb51"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\cxkp-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: a746ba8924442de46987f7811e4a49c3701df639.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C8%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005081601540561-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lB%2F7naFosJ3wWhYekKp8lcgIdJHoR4DsG9%2F8oJ5BCLA%3D&st=2020-05-08T15%3A57%3A33Z&se=2020-06-08T16%3A02%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[ad9ea67](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/ad9ea6715930d52cd2a67467fd494e7ba40e71df)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cb1152d6)

<a id="cb1152d6"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\j1i4-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: ad9ea6715930d52cd2a67467fd494e7ba40e71df.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C9%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005091557212290-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=63%2FnPq1WWjPOWFTvaregSVxdrH0aulczPyT7jwDvN48%3D&st=2020-05-09T15%3A52%3A58Z&se=2020-06-09T15%3A57%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[5753479](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/575347953c8ee6c006ee727a32c3699fe00b4373)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c415f595)

<a id="c415f595"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\mhzn-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 575347953c8ee6c006ee727a32c3699fe00b4373.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C9%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005091604069081-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ALWAS9koWfvvQgASV9v8m3FuC5brPIN1oiO9mYEP9u8%3D&st=2020-05-09T15%3A59%3A47Z&se=2020-06-09T16%3A04%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[1821b5e](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/1821b5e3835893163756a1d01b3c5d2e9640ad8d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-39867fb8)

<a id="39867fb8"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\fvla-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 1821b5e3835893163756a1d01b3c5d2e9640ad8d.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C9%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005091623298567-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GWKk%2FxI4sOZHGVGbAtFLulSoxRCpqG%2F1roNKk5sB3dY%3D&st=2020-05-09T16%3A19%3A11Z&se=2020-06-09T16%3A24%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[63d3b98](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/63d3b9838570da97d51e06a6d7a29a4bbd7b6f76)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3bc951eb)

<a id="3bc951eb"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\2ap2-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 63d3b9838570da97d51e06a6d7a29a4bbd7b6f76.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C9%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005091624551380-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ADCec7HMQFXhAqhG%2BOxfYfWYHud6Wnxo8FB0YC8esCM%3D&st=2020-05-09T16%3A20%3A36Z&se=2020-06-09T16%3A25%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[0c3ad3b](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/0c3ad3b037e73caeda851ed4dd635e324aabedda)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d344dda5)

<a id="d344dda5"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\te0w-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 0c3ad3b037e73caeda851ed4dd635e324aabedda.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C11%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005111253269514-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HztIuMVsiTOkVJcX%2BUm3LhGq4KkD2zQ2G4%2F0pzAhVs8%3D&st=2020-05-11T12%3A49%3A08Z&se=2020-06-11T12%3A54%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[8b4aaf6](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/8b4aaf6aa947f7953e0e0070824ead2b16ae7a39)_: 

:clock10: **Pending**: waiting for processors ([34](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 34 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[8b4aaf6](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/8b4aaf6aa947f7953e0e0070824ead2b16ae7a39)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c089aa2b)

<a id="c089aa2b"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\vh1c-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 8b4aaf6aa947f7953e0e0070824ead2b16ae7a39.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C11%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005112306329978-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wBbjTIam5z4VW0Hzg603dKWADv0MWrd5io3caEroC1Q%3D&st=2020-05-11T23%3A06%3A42Z&se=2020-06-11T23%3A11%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[147e4b5](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/147e4b5cfe018209265cbd0bd2f63823f7dc2b6a)_: 

:clock10: **Pending**: waiting for processors ([55](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 55 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[147e4b5](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/147e4b5cfe018209265cbd0bd2f63823f7dc2b6a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-71097ebb)

<a id="71097ebb"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\wpma-s, target branch: live-based414, target branch commit: 513e096bf365792732be1ff82d58c657969f7c21, source commit: 147e4b5cfe018209265cbd0bd2f63823f7dc2b6a.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C12%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202005120106235737-60%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RBbZuRuZN3%2BNOAAgwnuvrU4qooRN9EFtK2TemtF0zbc%3D&st=2020-05-12T01%3A23%3A29Z&se=2020-06-12T01%3A28%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
