### PR TITLE
Resolve syncing conflicts from from-prod-staging to staging

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from from-prod-staging to staging.

### CODE REVIEW

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[ddc90e8](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/ddc90e811bfe806b822ef9731b3746b9aed209b8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4fa61bba)

<a id="4fa61bba"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\oiju-s, target branch: HEAD, target branch commit: 36c8bc7df2f81bb4473c88b02ff5d1d81aa87a82, source commit: ddc90e811bfe806b822ef9731b3746b9aed209b8.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C24%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201908242049344208-20%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iCWtcb9vHddlDoQUe93UFRKKD87lNHVE1XSErbA8oZw%3D&st=2019-08-24T20%3A45%3A01Z&se=2019-09-24T20%3A50%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[895a78a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/895a78af15ccb8d4be861a39d0ea03ce5a3124d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-55a6b143)

<a id="55a6b143"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\x2mt-s, target branch: HEAD, target branch commit: 36c8bc7df2f81bb4473c88b02ff5d1d81aa87a82, source commit: 895a78af15ccb8d4be861a39d0ea03ce5a3124d2.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201908261731416481-20%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GvbLal9eHd3lrjGohKIKpt4%2F46WV6guJdHNgyelkM9o%3D&st=2019-08-26T17%3A27%3A10Z&se=2019-09-26T17%3A32%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[0888f52](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/0888f526746f2b8149b0b60f0088ea5b73ba974a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6b81ad5a)

<a id="6b81ad5a"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\cczn-s, target branch: HEAD, target branch commit: 36c8bc7df2f81bb4473c88b02ff5d1d81aa87a82, source commit: 0888f526746f2b8149b0b60f0088ea5b73ba974a.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201908261816496572-20%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w16Tb1%2BcUoc9flz97NSyK9G6brLnrkfJ4bSefb9y6Rc%3D&st=2019-08-26T18%3A12%3A30Z&se=2019-09-26T18%3A17%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[6b8ebdf](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/6b8ebdfdcc53e38fea4a6ef939552af95f42acd3)_: 

:clock10: **Pending**: waiting for processors ([29](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 29 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[6b8ebdf](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/6b8ebdfdcc53e38fea4a6ef939552af95f42acd3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/.openpublishing.redirection.json) | :warning:Warning | | [Details](#user-content-10516278-57cdaf9f)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-developer-docs/cmdlet/creating-a-cmdlet-to-access-a-data-store?branch=pr-en-us-20) |
[reference/3.0/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/3.0/Microsoft.PowerShell.Utility/Select-String.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/select-string?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/4.0/Microsoft.PowerShell.Utility/Select-String.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/select-string?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/5.0/Microsoft.PowerShell.Utility/Select-String.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/select-string?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/5.1/Microsoft.PowerShell.Utility/Select-String.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/select-string?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/6/Microsoft.PowerShell.Utility/Select-String.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/select-string?view=powershell-6&branch=pr-en-us-20) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Show-Markdown.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/6/Microsoft.PowerShell.Utility/Show-Markdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/show-markdown?view=powershell-6&branch=pr-en-us-20) (powershell-6) |
[reference/7/Microsoft.PowerShell.Utility/Select-String.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/7/Microsoft.PowerShell.Utility/Select-String.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/select-string?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/7/Microsoft.PowerShell.Utility/Show-Markdown.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/7/Microsoft.PowerShell.Utility/Show-Markdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/show-markdown?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/audit-and-report.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/audit-and-report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/audit-and-report?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/audit-and-report?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/audit-and-report?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/audit-and-report?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/audit-and-report?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/audit-and-report?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/overview.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/overview?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/overview?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/overview?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/overview?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/overview?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/overview?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/prerequisites.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/prerequisites?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/prerequisites?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/prerequisites?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/prerequisites?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/prerequisites?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/prerequisites?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/register-jea.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/register-jea.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/register-jea?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/register-jea?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/register-jea?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/register-jea?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/register-jea?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/register-jea?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/role-capabilities.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/role-capabilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/security-considerations.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/security-considerations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/security-considerations?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/security-considerations?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/security-considerations?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/security-considerations?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/security-considerations?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/security-considerations?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/session-configurations.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/session-configurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/session-configurations?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/session-configurations?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/session-configurations?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/session-configurations?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/session-configurations?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/session-configurations?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/learn/remoting/jea/using-jea.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/learn/remoting/jea/using-jea.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/using-jea?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/using-jea?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/using-jea?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/using-jea?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/using-jea?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/using-jea?view=powershell-7&branch=pr-en-us-20) (powershell-7) |
[reference/docs-conceptual/toc.yml](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-3.0&branch=pr-en-us-20) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-4.0&branch=pr-en-us-20) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-5.0&branch=pr-en-us-20) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-5.1&branch=pr-en-us-20) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-6&branch=pr-en-us-20) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/learn/remoting/jea/role-capabilities?view=powershell-7&branch=pr-en-us-20) (powershell-7) |

<a id="10516278-57cdaf9f"></a>
### [.openpublishing.redirection.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/.openpublishing.redirection.json)
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/audit-and-report.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/overview.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/prerequisites.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/register-jea.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/role-capabilities.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/security-considerations.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/session-configurations.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````
 - **[Warning]** `````Master redirection file .openpublishing.redirection.json has a redirection rule on file 'jea/using-jea.md'. However, the file already exists in the Git repo in conflict with the redirection rule. Docs will ignore the file and populate with the redirection rule instead. To resolve this warning, please remove the original file in Git repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C27%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201908270322349017-20%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GY1J51s8jJxRhfSyXb6tF5A1R8ApUX1ZLmehZ96FRn8%3D&st=2019-08-27T03%3A27%3A38Z&se=2019-09-27T03%3A32%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
