### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[4166f72](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/4166f72bcd611f0a1aa17958d47b9fc822ea4eb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C13%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004130628228668-58%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3piDhu7%2BsT%2BGDouMbSqHTlGIfiY9QsHmDOBreYQUJxw%3D&st=2020-04-13T06%3A32%3A40Z&se=2020-05-14T06%3A37%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1db381f](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/1db381ff063e1b6e96fe90e39ebfa6940dffe575)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1db381f](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/1db381ff063e1b6e96fe90e39ebfa6940dffe575)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1db381f](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/1db381ff063e1b6e96fe90e39ebfa6940dffe575)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/CimCmdlets/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/reference/5.1/CimCmdlets/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/cimcmdlets/testingpullrequest?view=powershell-5.1&branch=pr-en-us-58) (powershell-5.1) | [Details](#user-content-6a687d31-6d611180)
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md) | :white_check_mark:Succeeded | |

<a id="6a687d31-6d611180"></a>
### [reference/5.1/CimCmdlets/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/reference/5.1/CimCmdlets/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/5.1/nonexisted1.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/5.1/nonexisted2.md).`````
 - **Line 10**: **[Warning]** `````Invalid file link:(~/5.1/nonexisted3.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C13%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004131027109576-58%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r8ADzAq0T7y3jbbqoAMTtgfDWGoV4yyo8EpJxqcCD2o%3D&st=2020-04-13T10%3A31%3A08Z&se=2020-05-14T10%3A36%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[1db381f](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/1db381ff063e1b6e96fe90e39ebfa6940dffe575)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/CimCmdlets/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/reference/5.1/CimCmdlets/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/cimcmdlets/testingpullrequest?view=powershell-5.1&branch=pr-en-us-58) (powershell-5.1) | [Details](#user-content-6a687d31-37193d02)
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md) | :white_check_mark:Succeeded | |

<a id="6a687d31-37193d02"></a>
### [reference/5.1/CimCmdlets/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/reference/5.1/CimCmdlets/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/5.1/nonexisted1.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/5.1/nonexisted2.md).`````
 - **Line 10**: **[Warning]** `````Invalid file link:(~/5.1/nonexisted3.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C13%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202004131027265585-58%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=byVrVWtFDCpKUo7EX2QyavXkHC6P%2FplpaGGoOXpcuaM%3D&st=2020-04-13T10%3A40%3A11Z&se=2020-05-14T10%3A45%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
