### PR TITLE
Resolve syncing conflicts from repo_sync_novalidation_staging_branch to staging-nometavalidation

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_novalidation_staging_branch to staging-nometavalidation.

### CODE REVIEW

**Comment by v-susu** [comment]
Docs Build status updates of commit _[f615eee](https://github.com/OPS-E2E-Prod/PowerShell-Docs/pull/8/commits/f615eeed813e549a556ae254c9354fbcdccb5efe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2cb6aac4)

<a id="2cb6aac4"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\eirk-s, target branch: staging-nometavalidation, target branch commit: 2874667a52e6801547b7097348e364389a0e32ef, source commit: f615eeed813e549a556ae254c9354fbcdccb5efe.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201905140334419027-8%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ya%2FjMpVSIgGT1o7u95kOyzH9O80ZXGbGdR0xFvkJNMU%3D&st=2019-05-14T03%3A29%3A55Z&se=2019-06-14T03%3A34%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
Docs Build status updates of commit _[7dcfdad](https://github.com/OPS-E2E-Prod/PowerShell-Docs/pull/8/commits/7dcfdad58e3d1bf9861185b2950a3e403db7e07a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4aae4f38)

<a id="4aae4f38"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\jccr-s, target branch: staging-nometavalidation, target branch commit: 2874667a52e6801547b7097348e364389a0e32ef, source commit: 7dcfdad58e3d1bf9861185b2950a3e403db7e07a.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201905140337553294-8%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9P%2BfAQeCuDK1y74sbRnpyGHep0L%2F%2B%2B8jjcvo7eoRsQQ%3D&st=2019-05-14T03%3A33%3A09Z&se=2019-06-14T03%3A38%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
Docs Build status updates of commit _[6ba5d44](https://github.com/OPS-E2E-Prod/PowerShell-Docs/pull/8/commits/6ba5d4486834e09bc3f090f235cf21c4491e4c12)_: 

:clock10: **Full build**: the average full build time is _17 min(s) 46 sec(s)_, this is based on the last _4_ build(s) for this repository.

 :warning: **This is a FULL build** due to the 'staging-nometavalidation' branch being a new branch in Docs Build service and is still building, or there are build errors in 'staging-nometavalidation' branch so the cache for incremental build is not available. Normally no action is required on your part, but if the full build persists, please contact your repository admin to manually perform a full build on the 'staging-nometavalidation' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[6ba5d44](https://github.com/OPS-E2E-Prod/PowerShell-Docs/pull/8/commits/6ba5d4486834e09bc3f090f235cf21c4491e4c12)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C14%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201905140535394478-8%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ezoPTUwlFBBn45vrgoCj9QUzo2ctBH8Y%2FMAyamGp2LI%3D&st=2019-05-14T05%3A48%3A44Z&se=2019-06-14T05%3A53%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
