### PR TITLE
Merge master into live-based

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[f78b3d8](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/f78b3d8dfdd108bdd6edbee969c6be8058cefa20)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0553fb34)

<a id="0553fb34"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\bh5g-s, target branch: live-based, target branch commit: fe60c8dc0522109c2c29016ff623f31c6701aa38, source commit: f78b3d8dfdd108bdd6edbee969c6be8058cefa20.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202002190722167059-47%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=45Ga7%2Fx62qWl7683znTYr1zL1enCqo4DtqakoBj0Z3c%3D&st=2020-02-19T07%3A18%3A05Z&se=2020-03-21T07%3A23%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[2a4bdfe](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/2a4bdfe44dd992ec90004d13ec2ff3e0fd944c11)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b476a221)

<a id="b476a221"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\11w4-s, target branch: live-based, target branch commit: fe60c8dc0522109c2c29016ff623f31c6701aa38, source commit: 2a4bdfe44dd992ec90004d13ec2ff3e0fd944c11.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202002191703333810-47%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DKDFQS3pF6sOFhWZku8AvRFdCU96AIssWxX%2BOTtiK%2Bw%3D&st=2020-02-19T16%3A59%3A14Z&se=2020-03-21T17%3A04%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[358b00a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/358b00a1c7128321af2e8c35e98094ba8e484d64)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-60c9b147)

<a id="60c9b147"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\i3th-s, target branch: live-based, target branch commit: fe60c8dc0522109c2c29016ff623f31c6701aa38, source commit: 358b00a1c7128321af2e8c35e98094ba8e484d64.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202002191725206508-47%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zGRQf47Ob3E52tXMivwzoMAWpPrAHwZktOfiUqibMIk%3D&st=2020-02-19T17%3A21%3A01Z&se=2020-03-21T17%3A26%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[358b00a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/358b00a1c7128321af2e8c35e98094ba8e484d64)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-18a46775)

<a id="18a46775"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\mac1-s, target branch: live-based, target branch commit: fe60c8dc0522109c2c29016ff623f31c6701aa38, source commit: 358b00a1c7128321af2e8c35e98094ba8e484d64.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C20%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202002200535119027-47%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j8kECLux99YMyD4VskQQ1e7psM9nptEzAp9qC%2Bfchpo%3D&st=2020-02-20T05%3A31%3A03Z&se=2020-03-22T05%3A36%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[358b00a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/358b00a1c7128321af2e8c35e98094ba8e484d64)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9a462ca7)

<a id="9a462ca7"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\zckz-s, target branch: live-based, target branch commit: fe60c8dc0522109c2c29016ff623f31c6701aa38, source commit: 358b00a1c7128321af2e8c35e98094ba8e484d64.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C20%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202002200603302274-47%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GMdqwk80HXhWFpW23u1xtNG886n2aa4Fxo1kGqjXMbE%3D&st=2020-02-20T05%3A59%3A18Z&se=2020-03-22T06%3A04%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[c1bafdf](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/c1bafdfbefb079fe8d36ebe28255f3e3e3e3b457)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) | [Details](#user-content-429480bf-137e1796)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) | [Details](#user-content-baae884b-137e1796)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_scopes?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) | [Details](#user-content-ef223820-137e1796)
[reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6&branch=pr-en-us-47) (powershell-6) | [Details](#user-content-69dabe52-137e1796)
[reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-6&branch=pr-en-us-47) (powershell-6) | [Details](#user-content-ed0f2ce3-137e1796)
[reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_scopes?view=powershell-6&branch=pr-en-us-47) (powershell-6) | [Details](#user-content-4fb6798f-137e1796)
[reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7&branch=pr-en-us-47) (powershell-7) | [Details](#user-content-60445b91-137e1796)
[reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-7&branch=pr-en-us-47) (powershell-7) | [Details](#user-content-2d82bee2-137e1796)
[reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_scopes?view=powershell-7&branch=pr-en-us-47) (powershell-7) | [Details](#user-content-33a97bbe-137e1796)
[reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) | [Details](#user-content-74536769-137e1796)
[reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) | [Details](#user-content-9ff89903-137e1796)
[reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) | [Details](#user-content-58bd9879-137e1796)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[assets/Powershell_7_Infographic.pdf](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/assets/Powershell_7_Infographic.pdf) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Management/New-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/New-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/new-itemproperty?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Management/Set-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Set-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/set-itemproperty?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/register-engineevent?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-6&branch=pr-en-us-47) (powershell-6) |
[reference/6/Microsoft.PowerShell.Management/New-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/New-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/new-itemproperty?view=powershell-6&branch=pr-en-us-47) (powershell-6) |
[reference/6/Microsoft.PowerShell.Management/Set-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Set-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/set-itemproperty?view=powershell-6&branch=pr-en-us-47) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Register-EngineEvent.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Register-EngineEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/register-engineevent?view=powershell-6&branch=pr-en-us-47) (powershell-6) |
[reference/7.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7&branch=pr-en-us-47) (powershell-7) |
[reference/7.0/Microsoft.PowerShell.Management/New-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/New-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/new-itemproperty?view=powershell-7&branch=pr-en-us-47) (powershell-7) |
[reference/7.0/Microsoft.PowerShell.Management/Set-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Management/Set-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/set-itemproperty?view=powershell-7&branch=pr-en-us-47) (powershell-7) |
[reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7&branch=pr-en-us-47) (powershell-7) |
[reference/7.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/register-engineevent?view=powershell-7&branch=pr-en-us-47) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) |
[reference/7.1/Microsoft.PowerShell.Management/New-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/New-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/new-itemproperty?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) |
[reference/7.1/Microsoft.PowerShell.Management/Set-ItemProperty.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Management/Set-ItemProperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/set-itemproperty?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) |
[reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) |
[reference/7.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.utility/register-engineevent?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) |
[reference/digital-art.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/digital-art.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/digital-art?branch=pr-en-us-47) |
[reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-3.0&branch=pr-en-us-47) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-4.0&branch=pr-en-us-47) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-5.0&branch=pr-en-us-47) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-5.1&branch=pr-en-us-47) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-6&branch=pr-en-us-47) (powershell-6)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-7&branch=pr-en-us-47) (powershell-7)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/developer/cmdlet/how-to-support-jobs?view=powershell-7.x&branch=pr-en-us-47) (powershell-7.x) |

<a id="429480bf-137e1796"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="baae884b-137e1796"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="ef223820-137e1796"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="69dabe52-137e1796"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="ed0f2ce3-137e1796"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="4fb6798f-137e1796"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="60445b91-137e1796"></a>
### [reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="2d82bee2-137e1796"></a>
### [reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="33a97bbe-137e1796"></a>
### [reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="74536769-137e1796"></a>
### [reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="9ff89903-137e1796"></a>
### [reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

<a id="58bd9879-137e1796"></a>
### [reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C20%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202002200606309703-47%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4hARkMdwoMbz7ja12P3dbNLKVvFrFLTHEUzIHTgxo9s%3D&st=2020-02-20T06%3A09%3A08Z&se=2020-03-22T06%3A14%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
