### PR TITLE
Resolve syncing conflicts from from-prod-staging to staging

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from from-prod-staging to staging.

### CODE REVIEW

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[e79e67b](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/e79e67b4ce6e577c2a40a8af3817fd219ef7553e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-96b82bab)

<a id="96b82bab"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\x04m-s, target branch: staging, target branch commit: db1a5226953928afb8a2b5624934c17eb224ec3e, source commit: e79e67b4ce6e577c2a40a8af3817fd219ef7553e.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202009162107563878-73%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B28s3sEHiYI%2FnPqOz5e2Dz88L1KzNoCrqNevlDqcRj4%3D&st=2020-09-16T21%3A03%3A31Z&se=2020-10-17T21%3A08%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b970f9ed-4462-fae5-4090-7c9457391c1c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[a5b6dd7](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/a5b6dd7e1a94d3fa5768652bfe3e2ea3a476b63c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-03e5c909)

<a id="03e5c909"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\kc2q-s, target branch: staging, target branch commit: db1a5226953928afb8a2b5624934c17eb224ec3e, source commit: a5b6dd7e1a94d3fa5768652bfe3e2ea3a476b63c.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202009162227030987-73%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KYCM6nYk%2B7l0%2BQzNCPmd6liq9c%2Bqp5xgbD2pUY001%2FE%3D&st=2020-09-16T22%3A22%3A35Z&se=2020-10-17T22%3A27%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b970f9ed-4462-fae5-4090-7c9457391c1c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[0d116c7](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/0d116c7ee042649177cb67ae7fa753d708a918d9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6bdae432)

<a id="6bdae432"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\yxv3-s, target branch: staging, target branch commit: db1a5226953928afb8a2b5624934c17eb224ec3e, source commit: 0d116c7ee042649177cb67ae7fa753d708a918d9.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202009162231578466-73%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z2eTCpHFJBhzi0DwnJTGsKhbDkxbSJfG7UoD3HLdcbk%3D&st=2020-09-16T22%3A27%3A35Z&se=2020-10-17T22%3A32%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b970f9ed-4462-fae5-4090-7c9457391c1c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[eba02fc](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/eba02fcb3571511a8893c522043b5b49deefcef6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d003dfba)

<a id="d003dfba"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/PowerShell-Docs, working directory: W:\e0em-s, target branch: staging, target branch commit: db1a5226953928afb8a2b5624934c17eb224ec3e, source commit: eba02fcb3571511a8893c522043b5b49deefcef6.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202009170150236925-73%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tEkTHkytthVO66v4tt%2Fm7AWnoxZ%2FXTTJbKMh6jjY8c0%3D&st=2020-09-17T01%3A45%3A56Z&se=2020-10-18T01%3A50%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b970f9ed-4462-fae5-4090-7c9457391c1c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[ab6bbf9](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/ab6bbf9cb9160ea02cf0759be3cbd957b50462e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-c802de9d)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Management/Stop-Process.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/5.1/Microsoft.PowerShell.Management/Stop-Process.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/stop-process?view=powershell-5.1&branch=pr-en-us-73) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Management/Stop-Process.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/6/Microsoft.PowerShell.Management/Stop-Process.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/stop-process?view=powershell-6&branch=pr-en-us-73) (powershell-6) |
[reference/7.0/Microsoft.PowerShell.Management/Stop-Process.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/7.0/Microsoft.PowerShell.Management/Stop-Process.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/stop-process?view=powershell-7&branch=pr-en-us-73) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Management/Stop-Process.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/7.1/Microsoft.PowerShell.Management/Stop-Process.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/module/microsoft.powershell.management/stop-process?view=powershell-7.1&branch=pr-en-us-73) (powershell-7.1) |
[reference/docfx.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docfx.json) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/community/2020-Q3.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/docs-conceptual/community/2020-Q3.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-PowerShell_PowerShell-docs_reference/scripting/community/2020-q3?view=powershell-5.1&branch=pr-en-us-73) (>=powershell-5.1) |
[reference/mapping/monikerMapping.json](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/from-prod-staging/reference/mapping/monikerMapping.json) | :white_check_mark:Succeeded | |

<a id="c802de9d"></a>
###
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Core.Debug-Job' is defined with different summarys: '<p>Debugs a running background, remote, or PowerShell Workflow job.</p>
', '<p>Debugs a running background, remote, or Windows PowerShell Workflow job.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Core.Wait-Job' is defined with different summarys: '<p>Suppresses the command prompt until one or all of the PowerShell background jobs running in the session are completed.</p>
', '<p>Suppresses the command prompt until one or all of the Windows PowerShell background jobs running in the session are completed.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Management.Get-Service' is defined with different summarys: '<p>Gets the services on a local or remote computer.</p>
', '<p>Gets the services on the computer.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Management.Get-Clipboard' is defined with different summarys: '<p>Gets the contents of the clipboard.</p>
<p>[!NOTE]</p>
<blockquote>
<p>On Linux, this cmdlet requires the <code>xclip</code> utility to be in the path.</p>
</blockquote>
', '<p>Gets the current Windows clipboard entry.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Management.Get-Process' is defined with different summarys: '<p>Gets the processes that are running on the local computer or a remote computer.</p>
', '<p>Gets the processes that are running on the local computer.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Management.Get-PSProvider' is defined with different summarys: '<p>Gets information about the specified PowerShell provider.</p>
', '<p>Gets information about the specified Windows PowerShell provider.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Management.Set-Clipboard' is defined with different summarys: '<p>Sets the contents of the clipboard.</p>
', '<p>Sets the current Windows clipboard entry.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Utility.ConvertFrom-Json' is defined with different summarys: '<p>Converts a JSON-formatted string to a custom object or a hash table.</p>
', '<p>Converts a JSON-formatted string to a custom object.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Utility.ConvertTo-Csv' is defined with different summarys: '<p>Converts .NET objects into a series of character-separated value (CSV) strings.</p>
', '<p>Converts .NET objects into a series of comma-separated value (CSV) strings.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Utility.Add-Type' is defined with different summarys: '<p>Adds a Microsoft .NET Core class to a PowerShell session.</p>
', '<p>Adds a Microsoft .NET Framework class to a PowerShell session.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Utility.Write-Information' is defined with different summarys: '<p>Specifies how PowerShell handles information stream data for a command.</p>
', '<p>Specifies how Windows PowerShell handles information stream data for a command.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'PSDesiredStateConfiguration.Invoke-DscResource' is defined with different summarys: '<p>Runs a method of a specified DSC resource.</p>
', '<p>Runs a method of a specified PowerShell Desired State Configuration (DSC) resource.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'PSReadLine.Get-PSReadLineKeyHandler' is defined with different summarys: '<p>Gets the bound key functions for the PSReadLine module.</p>
', '<p>Gets the key bindings for the PSReadLine module.</p>
'.
`````
 - **Line 0, Column 0**: **[Warning-xref-property-conflict]** 
`````
UID 'Microsoft.PowerShell.Utility.Invoke-WebRequest' is defined with different summarys: '<p>Gets content from a web page on the Internet.</p>
', '<p>Gets content from a web page on the internet.</p>
'.
`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C202009170222156533-73%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i8yCbzPNm2LccNDrleA6BLhWAF4xPNrL25H2st85wvo%3D&st=2020-09-17T02%3A19%3A46Z&se=2020-10-18T02%3A24%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b970f9ed-4462-fae5-4090-7c9457391c1c?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
