### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[b46741a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/b46741acb3a9b298f6da446712a606eb660d6cb2)_: 

:clock10: **Pending**: waiting for processors ([17](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[b46741a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/b46741acb3a9b298f6da446712a606eb660d6cb2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-developer-docs/testingpullrequest?branch=pr-en-us-24) | [Details](#user-content-06f904d2-0114944e)

<a id="06f904d2-0114944e"></a>
### [developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/../nonexisted1.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/../nonexisted2.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/../nonexisted3.md).`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201908260804345326-24%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FLEtlItMGKxdzelB%2FHenholyUmBlGPW9lcZPAEo4zH8%3D&st=2019-08-26T08%3A11%3A11Z&se=2019-09-26T08%3A16%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[b46741a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/b46741acb3a9b298f6da446712a606eb660d6cb2)_: 

:clock10: **Pending**: waiting for processors ([27](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 27 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[b46741a](https://github.com/OPS-E2E-Prod/PowerShell-Docs/commits/b46741acb3a9b298f6da446712a606eb660d6cb2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/e2eprod-developer-docs/testingpullrequest?branch=pr-en-us-24) | [Details](#user-content-06f904d2-94d4ddfd)

<a id="06f904d2-94d4ddfd"></a>
### [developer/TestingPullRequest.md](https://github.com/OPS-E2E-Prod/PowerShell-Docs/blob/prtest/developer/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/../nonexisted1.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/../nonexisted2.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/../nonexisted3.md).`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C27%5Cb970f9ed-4462-fae5-4090-7c9457391c1c%5CPullRequest%5C201908270325305351-24%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6VO22uoU%2B3VYDX5ECApIHe3PQANMPreU1VNaRRxwi48%3D&st=2019-08-27T03%3A30%3A33Z&se=2019-09-27T03%3A35%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
